commit

diff --git a/bin/mkurl b/bin/mkurl
--- a/bin/mkurl
+++ b/bin/mkurl
@@ -1,14 +1,15 @@
 #!/bin/sh
 
 error() {
-    echo $(basename "$0")': '"$@" >&2
+    echo `basename "$0"`': '"$@" >&2
     exit 1
 }
 
 while [ "$1" ] ; do
     case "$1" in
         -h )
-            echo $(basename "$0")' TYPE [ARGS]...'
+            echo 'Usage: '`basename "$0"`' TYPE [ARGS]...'
+            echo 'Make urls from some words (like modern browser'\''s search engine bars.'
             exit
             ;;
 
@@ -42,21 +43,21 @@ case "$type" in
         argc 1 2
         case "$#" in
             1 )
-                elem=$(echo $1 | sed -e 's/_.*//')
-                num=$(echo $1 | sed -e 's/.*_//')
+                elem=`echo $1 | sed -e 's/_.*//'`
+                num=`echo $1 | sed -e 's/.*_//'`
                 ;;
             2 )
                 elem=$1
                 num=$2
                 ;;
         esac
-        [ -n "$elem" -a -n "$(echo "$num" | grep '^[[:digit:]]\+$')" ] || error "$type"': wrong format argument: '"$*"
+        [ -n "$elem" -a -n "`echo "$num" | grep '^[[:digit:]]\+$'`" ] || error "$type"': wrong format argument: '"$*"
         echo http://www1.axfc.net/uploader/"$elem"/so/"$num"
         ;;
 
     nicovideo | nico )
         argc 1
-        num=$(echo "$1" | grep '^\(sm\)\?[[:digit:]]\+$')
+        num=`echo "$1" | grep '^\(sm\)\?[[:digit:]]\+$'`
         [ "$num" ] || error "$type"': wrong format argument: '"$1"
         echo http://www.nicovideo.jp/watch/sm"$num"
         ;;
diff --git a/bin/pstrap b/bin/pstrap
--- a/bin/pstrap
+++ b/bin/pstrap
@@ -5,22 +5,26 @@ wait=1s # for sleep(1)
 # option
 while [ "$1" ] ; do
     case $1 in
-        -h | --help ) echo $(basename "$0")' [-w|--wait] [--] PID...' ; exit ;;
+        -h | --help )
+            echo 'Usage: '`basename "$0"`' [-w|--wait] [--] PID...'
+            echo 'Watch the process and terminate when they have died.'
+            echo 'e.g. use this to shutdown your PC after the end of cp(1).'
+            exit ;;
         -w ) wait="$2" ; shift 2 ;;
         -- ) shift ; break ;;
-        -* ) $(basename "$0")': unknown option: '"$1" >&2 ; exit 1 ;;
+        -* ) `basename "$0"`': unknown option: '"$1" >&2 ; exit 1 ;;
         * ) break ;;
     esac
 done
 
 if [ $# -eq 0 ] ; then
-    echo $(basename "$0")': missing argument' >&2
+    echo `basename "$0"`': missing argument' >&2
     exit 1
 fi
 
 for arg in "$@"; do
     if echo "$arg" | grep -v '^[[:digit:]]\+$' >/dev/null 2>&1; then
-        echo $(basename "$0")': wrong argument (a PID required): '"$arg" >&2
+        echo `basename "$0"`': wrong argument (a PID required): '"$arg" >&2
         exit 1
     fi
 done
